### ISSUE TITLE
 Koenders Herbaijum generator update niet automatisch?

### ISSUE THREAD

**Issue by StefanDeWildt** [acaciawater/acaciadata#11]
Koenders Herbaijum lijkt niet meer automatisch geupdate te worden (http://spaarwater.acaciadata.com/admin/data/datasource/39/  --> laatste update op 1/10). Lijkt zelfde issue als eerder bij Koenders Borgsweer.

**Comment by smoquet** [comment]
bij mijn locale versie werkt het update script ook voor datasource 39
