### ISSUE TITLE
NMC pro datasource link 404

### ISSUE THREAD

**Issue by smoquet** [acaciawater/acaciadata#13]
De link in de beheerpagina naar de bovenste datasource levert een 404 op, terwijl hij wel ingelezen wordt door de generator(er staat namelijk een start en stop naast). Het bestand lijkt er dus te zijn, maar is niet bereikbaar vanuit de admin page. 

De ds met:
- kapotte link = automatisch gegenereerd
- werkende link = handmatig geplaatst

http://spaarwater.acaciadata.com/admin/data/datasource/4/?_changelist_filters=q%3Dnmc

**Comment by tkleinen** [comment]
Opgelost
