### ISSUE TITLE
data NMC Pro Borgsweer & Breezand

### ISSUE THREAD

**Issue by StefanDeWildt** [acaciawater/acaciadata#18]
Data NMC Pro Borgsweer komt niet meer sinds 23/09, en bij NMC Pro Breezand niet meer sinds 6/11.

Theo, jij had aangegeven dat dit waarschijnlijk door een bug komt en Stephane hier naar gaat kijken. Is dit als gebeurt? Wat is de stand van zaken?

Groet,
Stefan

**Comment by smoquet** [comment]
volgens mij heb ik het probleem opgelost, maar om het zeker te weten moet ik het nog op de server zelf uloaden en testen. probleem was een andere versie van pandas

**Comment by smoquet** [comment]
Het probleem lijkt opgelost te zijn, we houden het nog even in de gaten of het bij komende update ook goed gaat.

**Comment by StefanDeWildt** [comment]
Dank je Stephane.

Arjen en Mieke, aan dashboard te zien komt NMC Pro data dus weer binnen. Ik zal morgen en overmorgen voor de zekerheid nog eens controleren.


Met vriendelijke groet,
Stefan de Wildt
Acacia Water B.V.
Van Hogendorpplein 4
2805 BM Gouda

Telefoon: +31 (0)182-686242
Mobiel: +31 (0)6-30431032
Email: stefan.dewildt@acaciawater.com
Internet: www.acaciawater.com<http://www.acaciawater.com>

[cid:image001.png@01D25556.DE9E7240]
