### ISSUE TITLE
bijwerken .csv-bestand SW dashboard

### ISSUE THREAD

**Issue by StefanDeWildt** [acaciawater/acaciadata#19]
Dag Theo en/of Stephane,

Wekelijks werk ik handgemeten EC watermonsters in Herbaijum bij via het Spaarwater dashboard (http://spaarwater.acaciadata.com/admin/data/datasource/133/?_changelist_filters=generator__id__exact%3D17) door het uploaden van een bijgewerkt .csv-bestand. Als ik een nieuw .csv als bronbestand wil bijwerken krijg ik de volgende foutmelding:

ValueError at /admin/data/datasource/133/
 

Zouden jullie kunnen kijken wat er mis gaat?

**Comment by smoquet** [comment]
Mijn eigen locale spaarwater geeft niet dezelfde error, ik gebruik ook acaciadata master, niet validatie. Error gebeurt in admin.py op regel 151 (instance.save -> als de file open is = I/O error). Kan het moelijk debuggen, want ik heb andere db nodig om de validatie branch te gebruiken.

**Comment by tkleinen** [comment]
Opgelost
