### ISSUE TITLE
NMC pro data 

### ISSUE THREAD

**Issue by ASBurger** [acaciawater/acaciadata#21]
de NMC pro datasource van Borgsweer werkt de data niet bij.
Als ik bijwerken doe krijg ik de foutmelding:

AttributeError at /admin/data/series/

'Index' object has no attribute 'to_pydatetime'

Request Method: 	POST
Request URL: 	http://spaarwater.acaciadata.com/admin/data/series/?parameter__datasource__id__exact=4
Django Version: 	1.8.2
Exception Type: 	AttributeError
Exception Value: 	

'Index' object has no attribute 'to_pydatetime'

Exception Location: 	/var/www/vhosts/LVXD005.acaciadata.com/spaarwater.acaciadata.com/spaarwater/acacia/data/models.py in get_data, line 472
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6
Python Path: 	

['/var/www/vhosts/LVXD005.acaciadata.com/spaarwater.acaciadata.com/spaarwater',
 '/var/www/vhosts/LVXD005.acaciadata.com/spaarwater.acaciadata.com/spaarwater/env/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/home/theo/texelmeet/acaciadata']

Server time: 	woe, 11 Jan 2017 16:17:39 +0000

**Comment by smoquet** [comment]
Kan dit helaas niet oplossen nu.
Ik heb een andere versie van models.py. Ik ben nog bezig met grondwaterstandsvoorspelling, en een oude db. Als ik dit wil debuggen heb ik een andere versie nodig van de db, en moet ik deze weer terugzetten als ik met de gws voorseplling verder wil.

**Comment by tkleinen** [comment]
Opgelost
