### ISSUE TITLE
Koenders generator update niet automatisch

### ISSUE THREAD

**Issue by smoquet** [acaciawater/acaciadata#7]
Mail v Stefan
-          Koenders: Handmatig geupdate via de volgende link, zoals ik afgelopen weken ook heb gedaan (http://spaarwater.acaciadata.com/admin/data/datasource/?q=koenders&meetlocatie__id__exact=1). Nu is deze gegevensbron echter bijgewerkt (laatste data) t/m 21 oktober 2015. Hier gaat dus iets mis.
  o   @Theo of Stephane: kunnen jullie hier nog eens naar kijken. Fijnste als deze gegevensbron gewoon weer automatisch update en dit helemaal niet meer handmatig hoeft te gebeuren
  o   Ook graag controle waar data na 21/10/2015 is gebleven. Tot vrijdag 16 september ’16 kwam de data namelijk nog wel gewoon binnen via de handmatige updates van de gegevensbron/parameter

**Comment by StefanDeWildt** [comment]
Ik ben er inmiddels achter dat er iets mis moet zijn in het log-bestand zelf achter deze gegevensbron (S5071.LOG, locatie: http://spaarwater.acaciadata.com/admin/data/datasource/20/). Het bronbestand komt namelijk onderaan de lijst van bronbestanden te staan en geeft onder 'Rows' een '0' aan.

**Comment by tkleinen** [comment]
Opgelost. lag aan gedeeltelijke update op 27 juli

**Comment by StefanDeWildt** [comment]
Mooi!
