### ISSUE TITLE
Sommatie

### ISSUE THREAD

**Issue by ASBurger** [acaciawater/acaciadata#8]
Cumulatieve sommatie van de meerdere databronnen, zoals debieten van BE de Lier (Net opnieuw geactualiseerd) gaat niet altijd automatisch, en moet dan handmatig worden geupdate. Wat hier precies de oorzaak van is, is mij niet duidelijk.

**Comment by smoquet** [comment]
Geen fouten ontdekt

**Comment by ASBurger** [comment]
dat kan, maar dan blijft de vraag, wat de oorzaak is waarom het actualiseren niet automatisch wordt uitgevoerd :-)

**Comment by tkleinen** [comment]
Is dit nu opgelost?

**Comment by ASBurger** [comment]
Het lijkt er op van wel

Met vriendelijke groet,
Sieger Burger
Acacia Water B.V.
Van Hogendorpplein 4
2805 BM Gouda

Telefoon: +31 (0)182-686242
Mobiel: +31 (0)6-10341723
Email: sieger.burger@acaciawater.com
Internet: www.acaciawater.com<http://www.acaciawater.com>

[cid:image001.png@01D27CAA.DD54EA60]


Van: Theo Kleinendorst [mailto:notifications@github.com]
Verzonden: woensdag 1 februari 2017 14:31
Aan: acaciawater/acaciadata
CC: Sieger Burger; Author
Onderwerp: Re: [acaciawater/acaciadata] Sommatie (#8)


Is dit nu opgelost?
