### ISSUE TITLE
Dagsommatie 

### ISSUE THREAD

**Issue by ASBurger** [acaciawater/acaciadata#9]
Ik zie dat de dagsommen van de neerslag niet altijd goed gaan. Ik heb hier een controle grafiek voor aangemaakt: http://spaarwater.acaciadata.com/data/grafiek/261/
Hier kun je zien dat op dit moment de sommatie van de neerslag op 4, 5 en 8 september niet goed gaat. Op 13 september is de dagsom wel goed. 
Als ik de reeks opnieuw aanmaak komen er wel een goede data uit.

**Comment by smoquet** [comment]
We begrijpen het niet
